FROM microsoft/dotnet:1.1.2-sdk

ENV DOTNET_USE_POLLING_FILE_WATCHER 1

COPY ./src/Voidwell.API/Voidwell.API.csproj /tmp/Voidwell.API.csproj

WORKDIR /tmp

RUN dotnet restore

WORKDIR /Voidwell.API

ENTRYPOINT dotnet watch run
