FROM microsoft/dotnet:2.0.0-sdk

ENV DOTNET_USE_POLLING_FILE_WATCHER 1

COPY ./src/Voidwell.API/Voidwell.API.csproj /tmp
COPY ./Directory.Build.props /

WORKDIR /tmp

RUN dotnet restore

WORKDIR /app

ENTRYPOINT dotnet watch run --no-launch-profile