FROM mcr.microsoft.com/dotnet/core/sdk:2.2

ENV DOTNET_USE_POLLING_FILE_WATCHER 1
ENV ASPNETCORE_ENVIRONMENT Development

COPY ./src/Voidwell.API/*.csproj /tmp/

WORKDIR /tmp

RUN dotnet restore

WORKDIR /app/Voidwell.API

EXPOSE 5000

CMD [ "dotnet", "watch", "run", "--no-launch-profile" ]
